### ISSUE TITLE
ReactNative.createClass was deprecated since react-native 0.25.1

### ISSUE THREAD

**Issue by hardtack** [artemyarulin/ktoa#11]
Importing React's APIs from ReactNative was deprecated since RN 0.25.1 and not works on recent versions of RN. (https://github.com/facebook/react-native/releases/tag/v0.25.1)
In [this file](https://github.com/artemyarulin/ktoa/blob/master/src/ktoa/components.cljc#L10), there are code like this.

``` clojure
#?(:cljs
   (defn element [element opts & children]
     "Helper for React Native component: Allows developer to use
      clojure maps as component options and add multiple
      children"
     (apply (.-createElement core/react-native) element (clj->js opts) children)))
```

and it causes error like this

<img width="487" alt="2016-10-23 5 58 09" src="https://cloud.githubusercontent.com/assets/415292/19625116/4c618952-994a-11e6-8961-3b709af7a0aa.png">

**Comment by artemyarulin** [comment]
Hi, thank you for reporting that. Unfortunately I'm a bit busy right now, but as soon as I get more free time I'll fix that. Or you can make a PR which I will be happy to accept.
